language: php

php:
  - 7.0
  
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: 
    - ./vendor/bin/sami.php update --force ./test/sami.php
    - test -f ./test/build/index.html
